### ISSUE TITLE
out propagation condition declaration cannot reference outgoing subcomponent propagation

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/emv2#11]
When specifying error behavior for component implementations it is desirable to specify how the outgoing propagations of subcomponents producing the output affect the propagation.
Currently L40 limits the references in the condition to incoming propagations and error events (and error states as the left hand side).
Note that for error detection we do allow references to outgoing propagations from subcomponents.

Proposal: change of legality rule L40.

**Comment by jjhugues** [comment]
This change has been implemented in the document, we can close this issue
