### ISSUE TITLE
Grammar for EMV2 annex specific paths allows too much length

### ISSUE THREAD

**Issue by buzden** [saeaadl/emv2#18]
We have the following grammar in the standard:

```
emv2_containment_path ::=
     [ aadl2_core_path @ ] emv2_annex_specific_path

aadl2_core_path ::=
  named_element_identifier { . named_element_identifier }*

emv2_annex_specific_path ::=
  named_element_identifier { . named_element_identifier }*
```

Also we have to following naming rules. In "Error Model Subclauses" section:

> The emv2_annex_specific_path may end with a reference to an error type associated with the previous error model element.

In "Error Behavior State Machines" section.

> The `emv2_annex_specific_path` of an `emv2_contained_property_association` in an error behavior state machine properties section **must consist of reference to an error event, recover event, repair event, error state, or error state transition identifier** that is defined in the namespace of the Error Behavior State Machine. For error events and error states this reference **may optionally be followed by an `error_type_reference`**, separated by a dot (“.”).This error type reference must be an error type included in the error type set associated with the error event or error state.

Thus, `emv2_annex_specific_path` can consist only of a single event/state/transition identifier and optionally a single type identifier.

What is completely unclear is that why then `emv2_annex_specific_path` has a grammar definition allowing arbitrarily long list of identifiers separated with dots. It seems that in the grammar rule for `emv2_annex_specific_path` we should replace `{` and `}*` with `[` and `]` (optionality).

**Comment by reteprelief** [comment]
This is a leftover from the time where we had not settled yet on revising the path notation from the core language. We supported the path with just the dot notation. 
See also #20.

**Comment by reteprelief** [comment]
in propagation of a feature group element leads to multiple dotted names before the type.

**Comment by jjhugues** [comment]
@lwrage can you please review this change?

**Comment by lwrage** [comment]
Peter's last comment is correct. We need the long paths because an error propagation can be identifed by a dotted name. The proposed change would break things so we should not accept it.

**Comment by jjhugues** [comment]
OK, so I presume the errata is not valid and that the enhancement tag is erroneous
