### ISSUE TITLE
Grammar for type reference in EMV2 annex specific path

### ISSUE THREAD

**Issue by buzden** [saeaadl/emv2#19]
As it written in the annex, `emv2_annex_specific_path`

> may optionally be followed by an `error_type_reference`, separated by a dot (“.”)

We think that dot-separation syntax is not adequate for type reference because type is not a part of a referenced event or state. We propose to change the syntax to make type references to be easily distinguishable from subcomponents references or similar things.

I.e. we'd like to see something like `state{type}` instead of `state.type`.

**Comment by reteprelief** [comment]
I like the idea. However, this is a syntactic change

**Comment by buzden** [comment]
> However, this is a syntactic change

We really consider this change worth to be done.

You know, in context of AADL we talk so much about early validation and verification of modelled systems to avoid errors on early stages of development because such errors may lead to a lot of rework on further stages. 

But what if we are making similar mistake by saying "However, this is a syntactic change" in the modelling language? Don't you think that not making this syntactic change will lead to much worse results?

**Comment by reteprelief** [comment]
Denis,

I personally agree with you. I just sometimes get complaints about the stability of the standard.

I plan to discuss this errata at the meeting.
