### ISSUE TITLE
Inconsistency between grammar and semantics definition of error_source

### ISSUE THREAD

**Issue by buzden** [saeaadl/emv2#21]
In grammar for `error_source` we can see
```
error_source ::=
    defining_error_source_identifier :
      error source ( outgoing_error_propagation_point | all )
      [ effect_error_type_set ] [ when fault_source ] [ if fault_condition ] ;
```

In semantics section it is written
> An error source declaration may include a specification of the failure mode or event (expressed by a **with**) ...

In grammar "**when**" is used but in the semantics section "**with**" is used. It seems that one should be corrected.

**Comment by reteprelief** [comment]
Thanks. With should be When.
