### ISSUE TITLE
Using of typed things without types

### ISSUE THREAD

**Issue by buzden** [saeaadl/emv2#22]
We have in the standard

> An error event _may be declared with_ an error type that represents a type hierarchy. …

and

> An error behavior state _may be declared with_ an error type or type set. ...

Standard does not prohibit using of typed events and states (e.g. in a transitions) without mentioning any type. What is the semantics of this usage? Is this referencing to all "substates"/"subevents"?

**Comment by reteprelief** [comment]
The optional error type set on an incoming propagation or error behavior state in a condition expression acts as a constraint on the error types that  trigger the transition. If not present all error types specified with the error event, incoming propagation or error behavior state are candidates.
