### ISSUE TITLE
Unclear "current" and "unique" notions used in one consistency rule

### ISSUE THREAD

**Issue by buzden** [saeaadl/emv2#23]
In the **Component Error Behavior Specification** section it is written that

> For the current error behavior state there must be one unique outgoing transition.

Which state is called **current** in this paragraph?
What is the meaning of **one unique**? Which set the transition must be unique in?
What is the source state of the mentioned **outgoing** transition?

**Comment by reteprelief** [comment]
"current" is meant to say "any given state"
"one unique" is meant to say that there are no two transitions with the given state as source that can get triggered by a set of trigger conditions.
