### ISSUE TITLE
On ambiguity of error state transitions

### ISSUE THREAD

**Issue by buzden** [saeaadl/emv2#24]
We have the question to the _paragraph (12)_ of the _Error Behavior States and Transitions_ subsection of the _Error Behaviour State Machines_ section of the EMV2.

Are we correct to interpret the text

> The set of outgoing error behavior transitions ... must be unambiguous ..., i.e., they must uniquely identify the target state for a given state, error behavior events, and incoming error propagations.

as "each pairwise conjunction of conditions for transitions going out from each single state must be false"?

By the way, it is unclear where the following reference goes in this paragraph:

> The consistency rules expressing this can be found in Section Annex Document L.

**Comment by reteprelief** [comment]
It is intended to mean that for a given source state the conjunction of transition conditions to two different target states must be false.

The section reference should be to Section E.10 (in my copy it references E.9). There are several places with the incorrect reference.
