### ISSUE TITLE
Confusing semantics of XOR

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/emv2#27]
Example:
A1 XOR A2 XOR A3
In Boolean logic A1 T A2 T A3 T results in T
Intuitively users may expect multi-operand XOR semantics, i.e., only one of A1,A2,A3 is true

Proposal: k **of** ( A1,A2,A3)
follows **ormore** style.

**Comment by buzden** [comment]
Which expressions is this issue related to?

XOR implies a logical negation which is not present in FTA (as is was discussed in #15).

**Comment by lwrage** [comment]
This is a duplicate of #6
