### ISSUE TITLE
Typeset on right hand side should contain a single type

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/emv2#28]
check in document

**Comment by reteprelief** [comment]
the typeset on the right hand side of a transformation or out propagation declaration identifies the target type for a given set of incoming propagation types or error events. It should contain only a single type - otherwise we cannot uniquely identify which one gets propagated.

**Comment by lwrage** [comment]
This was already changed in the annex document by having syntax rule `target_error_type_instance` which is used with error paths, error transition target states, outgoing propagation conditions, type mappings, type transformations, etc.

**Comment by jjhugues** [comment]
Thanks; I can therefore consider this as closed
