### ISSUE TITLE
Allow expressions as elements of "ormore", "orless" expression

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/emv2#33]
currently users can only specify a single event, propagation. We should allow at least and expressions.
Note that "ormore" acts as inclusive or while "or" is an exclusive or.

**Comment by buzden** [comment]
> Note that "ormore" acts as inclusive or while "or" is an exclusive or.

Is it going to be changed as is was being discussed at #6 more than a year ago?

**Comment by jjhugues** [comment]
The intent seems to have
```
1 ormore (A and B, A and C)
```
This has been implemented and the BNF supports it. No action required
